lane :test do
  bluepill(
    app: 'path/to/SomeApp.app',
    scheme: 'path/to/SomeApp.xcscheme',
    output_dir: 'path/to/output_dir',
    device: 'iPhone 6',
    number_of_simulators: 2,
    headless: true,
    reuse_simulator: true
  )
end
